# Generated by Django 5.1.3 on 2025-02-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.CharField(choices=[('https://r00tus34.me/EnChat/EnChat/assests/1.png', 'https://r00tus34.me/EnChat/EnChat/assests/1.png'), ('https://r00tus34.me/EnChat/EnChat/assests/2.png', 'https://r00tus34.me/EnChat/EnChat/assests/2.png'), ('https://r00tus34.me/EnChat/EnChat/assests/3.png', 'https://r00tus34.me/EnChat/EnChat/assests/3.png'), ('https://r00tus34.me/EnChat/EnChat/assests/4.png', 'https://r00tus34.me/EnChat/EnChat/assests/4.png'), ('https://r00tus34.me/EnChat/EnChat/assests/5.png', 'https://r00tus34.me/EnChat/EnChat/assests/5.png'), ('https://r00tus34.me/EnChat/EnChat/assests/6.png', 'https://r00tus34.me/EnChat/EnChat/assests/6.png')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
