# Generated by Django 5.1.3 on 2025-02-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(choices=[('/media/default_profile_pics/__2.png', '/media/default_profile_pics/__2.png'), ('/media/default_profile_pics/__3.png', '/media/default_profile_pics/__3.png'), ('/media/default_profile_pics/__1.png', '/media/default_profile_pics/__1.png'), ('/media/default_profile_pics/__4.png', '/media/default_profile_pics/__4.png'), ('/media/default_profile_pics/__5.png', '/media/default_profile_pics/__5.png'), ('/media/default_profile_pics/__6.png', '/media/default_profile_pics/__6.png')], max_length=100),
        ),
    ]
